language: generic
os:
  - linux
  - osx
env:
  global:
    - CONDA_PREFIX=$HOME/conda
    - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
    - TRAVIS_PYTHON_VERSION="3.*"
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      OS="MacOSX-x86_64"
    else
      OS="Linux-x86_64"
    fi
  - curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -p $CONDA_PREFIX
  - export PATH="$CONDA_PREFIX/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --add channels conda-forge
  - conda install python=$TRAVIS_PYTHON_VERSION cmake fortran-compiler
  - conda activate root
install:
  - mkdir _build && cd _build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
  - make
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      - source ../.ci/travis/update_rpaths.sh
    fi
  - make install
script:
  - ctest
